FROM centos:7.0.1406

ENV JENKINS_HOME /home/jenkins
ARG user=jenkins 
ARG group=jenkins
ARG uid=1000
ARG gid=1000

RUN groupadd -g ${gid} ${group} \
    && useradd -d "$JENKINS_HOME" -u ${uid} -g ${gid} -m -s /bin/bash ${user}

RUN mkdir -p "$JENKINS_HOME"
RUN chown -R ${user}. "$JENKINS_HOME"

VOLUME [ "/home/jenkins_home" ]
USER ${user}
ENTRYPOINT sleep infinity
